= Loh Wei Jie, Oscar - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

This portfolio showcases my ability to produce functional code and documentation, for a team-based NUS
 software engineering project.

== PROJECT: NSync

---

== Overview

NSync is a desktop-based utility application used by NUS students, with tailored tools for timetable
coordination and notes acquisition, allowing for streamlining of work processes.

== Summary of contributions

* *Major enhancement*: Notes Deletion
** What it does: In a single command, the user is able to delete the notes previously downloaded using
 NSync, allowing him to quickly and conveniently free up storage space.
** Justification: Because my teammate has already implemented an automated notes downloader, allowing
the user to download large folders conveniently, it is important to have an equally convenient method
to delete notes.  This removes the need for the user to manually go to storage to delete his own
notes.
** Highlights: As this enhancement involves interaction with actual storage, a good understanding of
how `Model` and `Storage` components work together, is required.
Existing file manipulation libraries such as java.io and java nio libraries were incorporated into this
enhancement.

* *Minor enhancement*: Alphabetised contact list in the address book
** What it does: When the user adds a new contact to your contact list, the contact is added in an alphabetic
 order automatically.  This is opposed to the original implementation, which simply appends the new
 contact to the end of the contact list.
** Justification:  Alphabetisation allows the contact list to appear more organized.
** Highlights: Understanding of time complexity of algorithms is required.
For the sorting algorithms, the existing library java.util was incorporated.

* *Code contributed*: https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=auskure[Functional and test code]

* *Other contributions*:

** Project management: Successfully assigned and managed `issues` for all team members, and matched them to corresponding deadlines.

** Documentation: Organized the User Guide into a more reader friendly format +
https://github.com/CS2113-AY1819S1-W12-2/main/pull/61[#61]

** Community: Pull requests meticulously reviewed +
https://github.com/CS2113-AY1819S1-W12-2/main/pull/72[#72] +
https://github.com/CS2113-AY1819S1-W12-2/main/pull/148[#148]


== Contributions to the User Guide
|===
|_The following shows my contributions to the user guide, in relation to functions `clearNotes` and
`deleteSelectNotes`
They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=clearNotes]

include::../UserGuide.adoc[tag=deleteSelectNotes]

== Contributions to the Developer Guide

|===
|_The following shows my contributions to the user guide, in relation to the alphabetised contact list enhancement.
This showcases my ability to write technical documentation and the technical
   depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=storageComponent]

include::../DeveloperGuide.adoc[tag=sortingofpersons]
