= Hu Yi Qing - Project Portfolio
:imagesdir: ../images
:site-section: AboutUs
:stylesDir: ../stylesheets


== [blue]#PROJECT: NSync#

== [blue]#Overview#


NSync is a student lifestyle management and utility application built apon AddressBook - Level 4. The application uses a Command-Line interface to interact with the user. It aims to increase the efficiency of time consuming tasks that predominantly exist in a students life.

This document includes the contributions of Hu Yi Qing across the duration of the project.

== [blue]#Summary of contributions#
* *Major Enhancement* : Added the ability to download notes from IVLE automatically.


** What it does: Allows user to download all notes of a certain module using the `downloadAllNotes` command
or view all the available files and select which files to download with the `downloadSelectNotes` command.

** Justification: This feature streamlines notes downloads by simplifying it to 1-2 lines of command input.

** Highlights: Selenium Web-driver libraries is used to implement this feature. The libraries has several conflicts with the existing code base; which required special care to resolve.


** Credits: Selenium WebDriver.


* *Minor Enhancement* : Added the ability to view the notes download using the `showNotes`.

** What it does: Displays notes downloaded.

** Justification: User could view notes without going into directory

* *Code contributed* : [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=bearperson1[Functional Code and Test Code]]


* *Other Contributions :*
** Additional enhancements:
*** Implemented auto extraction of ChromeDrivers from the NSync.jar.
*** Implemented auto creation of additional file paths from NSync.jar.

** Community:


*** Reviewed multiple pull requests: (Examples: https://github.com/CS2113-AY1819S1-W12-2/main/pull/145[#145],
https://github.com/CS2113-AY1819S1-W12-2/main/pull/151[#151])

*** Reported bugs for other teams: (Examples:
https://github.com/CS2113-AY1819S1-T12-2/main/issues/154[1],
https://github.com/CS2113-AY1819S1-T12-2/main/issues/166[2])

*** Responded to bug reports: (Examples:
https://github.com/CS2113-AY1819S1-W12-2/main/issues/129[1],
https://github.com/CS2113-AY1819S1-W12-2/main/issues/128[2])

** Tools:

*** Integrated third party library (apache.commons.io) to project
*** Integrated third party library (Selenium WebDriver) to project


== [blue]#Contributions to the User Guide#

****
Displayed below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users.
****

'''

include::../UserGuide.adoc[tag=downloadCommands]
include::../UserGuide.adoc[tag=showNotesCommand]

== [blue]#Contributions to the Developer Guide#

****
Displayed below are sections I contributed to the Developer Guide. They showcase my ability to write documentation targeting Developers, as well as construct UML diagrams.
****

'''

include::../DeveloperGuide.adoc[tag=downloadCommands]
include::../DeveloperGuide.adoc[tag=showNotesCommand]
