= Hu Yi Qing - Project Portfolio
:imagesdir: ../images


== [blue]#PROJECT: NSync#

== [blue]#Overview#


NSync is a student lifestyle management and utility application built apon AddressBook - Level 4. The application uses a Command-Line interface to interact with the user. It aims to increase the efficiency of time consuming tasks that predominantly exist in a students life.

This document documents the contributions of Hu YiQing across the duration of the project.

== [blue]#Summary of contributions#
* *Major Enhancement* : Added ability to download notes from IVLE automatically.


** What it does: Allows the user to download all notes of a certain module using the `downloadAllNotes` command
as well as view all the available files and select which files to download with the `downloadSelectNotes` command.

** Justification: This feature will streamline notes downloads by simplifying it to 1 to 2 lines of command input.

** Highlights: We employed the Selenium Web-driver library to implement this feature. The libraries uses features that has several conflicts with the existing code base, which required special care to resolve.


** Credits: Selenium WebDriver.


* *Minor Enhancement* :  added the ability to view the notes download using the `showNotes`
//must have the same treatment as the major enchancement

* *Code contributed* : [https://github.com/BearPerson1/Michaels-ver-of-ab4[Functional Code]]


* *Other Contributions :*
** Project management:
*** Implemented auto extraction of ChromeDrivers from the .jar.
*** Implemented auto creation of additional file paths from .jar.

** Community:
*** Reported Bugs and requested request of special libraries (examples: https://github.com/nusCS2113-AY1819S1/forum/issues/71[1],
https://github.com/nusCS2113-AY1819S1/forum/issues/11[2])

*** Reviewed multiple pull requests: (Examples: https://github.com/CS2113-AY1819S1-W12-2/main/pull/145[#145],
https://github.com/CS2113-AY1819S1-W12-2/main/pull/151[#151],
https://github.com/CS2113-AY1819S1-W12-2/main/pull/150[#151])

*** Reported bugs for other teams: (Examples: https://github.com/CS2113-AY1819S1-T12-2/main/issues/178[1],
https://github.com/CS2113-AY1819S1-T12-2/main/issues/154[2],
https://github.com/CS2113-AY1819S1-T12-2/main/issues/166[3])

*** Responded to bug reports: (Examples:
https://github.com/CS2113-AY1819S1-W12-2/main/issues/129[1],
https://github.com/CS2113-AY1819S1-W12-2/main/issues/128[2])

** Documentation:
*** Added entries to the User Guide for `downloadAllNotes`,`downloadSelectNotes` and `showNotes` command.

** Tools:

*** Integrated third party library (apache.commons.io) to project
*** Integrated third party library (Selenium WebDriver) to project


== [blue]#Contributions to the User Guide#

****
Displayed below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users.
****

'''

include::../UserGuide.adoc[tag=downloadCommands]
include::../UserGuide.adoc[tag=showNotesCommand]

== [blue]#Contributions to the Developer Guide#

****
Displayed below are sections I contributed to the Developer Guide. They showcase my ability to write documentation targeting Developers, as well as construct UML diagrams.
****

'''

include::../DeveloperGuide.adoc[tag=downloadCommands]
include::../DeveloperGuide.adoc[tag=showNotesCommand]