= Lee Geng Yu - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

This portfolio documents my contributions to a NUS Software Engineering project.

== PROJECT: NSync

---

== Overview

NSync is a desktop application with a command-line interface that helps students resolve the problem of scheduling meetings between their peers, team mates and friends in a simple and fuss-free manner.

== Summary of contributions

* *Major enhancement*: Added the feature to *export and import user details*.
** What it does: Allows the user to `export` and `import` all the details of a particular contact. These details include the name, contact number, email, address and time-table of the contact.
** Justification: Each user has to key in their contacts' individual details previously, which is a very time-consuming process. This time-saving feature allows the user and his/her contacts to key in their own details in a one-time fashion, before exporting their own details and exchanging it with each other for importing.
** Highlights: This enhancement builds upon all of the existing user details, and requires an in-depth understanding of the workings of the `Logic` and `Model` components. The implementation required coalescing all of a user's details during exporting, as well as decoding it into the respective fields subsequently during importing.

* *Code contributed*: [https://nuscs2113-ay1819s1.github.io/dashboard/#=undefined&search=leegengyu[Functional and test code]]

* *Other contributions*:

** Project management:
*** Managed releases for NSync: `v1.2`, `v1.3`, `v1.3(PE)` on GitHub
*** Bug reports reviewed (with non-trivial review comments): All issues from #99 to #135

** Enhancements to existing features:
*** Stream-lined error-handling in terms of message displayed to users in the event of an incorrect command (To be updated)
*** Wrote additional tests for existing features and tests for new features, increasing coverage from x% to y% (To be updated)

** Documentation:
*** Added features coming in v2.0 in the User Guide (Pull Request #<To be added>)

** Community:
*** Contributed to forum discussions: #14, #27
*** Reported bugs and suggestions for team T09-4 in the class: #129, #131, #133, #136, #138, #140, #141, #143

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=freecommand]

include::../UserGuide.adoc[tag=exportcommand]

include::../UserGuide.adoc[tag=importcommand]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]
