= Lee Geng Yu - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: NSync

---

== Overview

NSync was created to help students resolve the issue of scheduling meetings between their peers, team mates and friends.

If you are a student, all you have to do is to key in your time-table (and get your friends to do so as well!) once, and we will find you your common meeting time-slot in a simple and fuss-free manner!

== Summary of contributions

* *Major enhancement*: added the feature to *export and import user details*
** What it does: allows the users to `export` and `import` all information fields of one or more contacts, which includes the name, contact number, email, address and the time-table itself.
** Justification: This feature boosts the productivity of the user significantly, by cutting down the amount of time that he/she has to take to input his/her contacts' details. The user and his/her contacts will only have to key in their contact details and time-tables respectively in a one-time fashion, before exporting their details and sending it to each other for importing.
** Highlights: This enhancement builds upon all of the existing user fields, requiring an in-depth analysis into the workings of the `Logic` and `Model` component. The implementation required coalescing all of a user's details during exporting, as well as decoding it into the respective fields subsequently during importing.

* *Minor enhancement*: added a `free` command that allows the user to find the next immediate available time-slot for himself, or his contacts from the current time.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** To be added.

** Enhancements to existing features:

** Documentation:
*** Added features coming in v2.0 in the User Guide (Pull Request #<To be added>)

** Community:
*** PRs reviewed: To be added.

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]
